version: '3.8'

services:
  db:
    image: mysql:8.0  # Specify the desired MySQL version
    environment:
      - MYSQL_ROOT_PASSWORD=root@123  # Consider using a stronger password
      - MYSQL_DATABASE=hospital # Replace with your desired database name
    ports:
      - "3306:3306"  # Map container port 3306 (MySQL default) to host port 3306
      

volumes:
  mysql-data: 
